### ISSUE TITLE
No 3.9.1 package provides libhsakmt.so.1

### ISSUE THREAD

**Issue by Dantali0n** [RadeonOpenCompute/ROCR-Runtime#108]
When upgrading from ROCm 3.9.0 to ROCm 3.9.1 on Debian, everyone system will be left in a broken state. No package provides libhsakmt.so.1 resulting in many `dlerror: libhsakmt.so.1: cannot open shared object file: No such file or directory` errors.

```
$ apt-file search libhsakmt.so.1

```

**Comment by xuhuisheng** [comment]
It caused by the installation issue of ROCm-3.9.1, please refer : https://github.com/RadeonOpenCompute/ROCm/issues/1289 .

**Comment by zhang2amd** [comment]
The install issue is caused by APT cache. During point release, the default APT repo "debian" was pointing to 3.9.1 but later reverted back to 3.9.0. If you have updated system (run 'apt update' command) during that time your APT cache may have the ROCm 3.9.1 package information.
Please clean up your system cache and install again. 
`apt clean
rm -rf /var/lib/apt/lists/*
apt update`
Then continue to install. Use "debian" or "3.9" for 3.9.0 release and use "3.9.1" for point release.
