### ISSUE TITLE
Source release for hsa-ext-rocr-dev

### ISSUE THREAD

**Issue by acowley** [RadeonOpenCompute/ROCR-Runtime#33]
In a container built using [`rocm-terminal`](https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/rocm-terminal/Dockerfile), I have a package `hsa-ext-rocr-dev` that includes `libhsa-ext-image64.so.1.1.7`. Is there a way to build this library from the available repositories?

**Comment by jlgreathouse** [comment]
Hi @acowley, Sorry for the long delay in responding to this.

Unfortunately, libhsa-ext-image64.so.1 is a closed-source library that we provide primarily for invulnerability with image types (such as in OpenCL). I include a bit more information [in my response to this ticket on the ROCm repo](https://github.com/RadeonOpenCompute/ROCm/issues/267).

As such, your choices at this time are either to not include it (and thus not offer image types in OpenCL) or pull the binary from our repo and include it directly.

To note, at this time `hsa-ext-rocr-dev` is the package for our closed-source extensions. Both of the libraries included in it in ROCm 1.9 are closed-source.

**Comment by acowley** [comment]
Thank you for following up, @jlgreathouse! Two (hopefully) quick questions:

1. Is there an expectation that OpenCL image support will be open sourced in the foreseeable future, or should we all get used to this being a binary-only release?

2. If we install the binary release, can we hope to have OpenGL texture <-> OpenCL Image sharing with a mainline kernel release? I understand this is one of the things advertised as a benefit of using the custom KFD kernel, but avoiding a custom kernel is hugely appealing with how far behind it lags (e.g. just now seeing a 4.15 release when upstream 4.19 is in testing). If this sharing doesn't work today, is it something we can hope will arrive in 4.19 or thereabouts?

**Comment by jlgreathouse** [comment]
Hi @acowley 

At this time, releasing the HSA images extension is not part of our public ROCm roadmap. We're always re-evaluating priorities, but as you're likely familiar with, there's a limited amount of development time our team can put into the project each release. As such, we have to pick and choose our battles. Right now, images work with our closed source HSA extension, but the OpenCL runtime correctly operates without this extension (by disabling support for image types in compute applications) for folks that do not want to deal with closed-source modules.

Your second question is a bit more nuanced. @fxkamd, @kentrussell, or @johnbridgman may be able to say this more accurately than me, but my understanding is as such: our goal is to get everything that is in the ROCm-specific driver modules upstreamed into the kernel at some point. However, rather than halt all development elsewhere in the stack while we wait for patches to go through code cleanup, community review, etc. we release features in the ROCK driver first. As such, ROCK is more of a "leading edge" of where we would like our upstream features to go. And the ROCK driver itself is open source, so we're not trying to hide anything with our ROCK release vs. upstream kernel.

That said, it can sometimes take a while between when we have a working open source implementation of a feature and when that implementation has been reworked to be acceptable into the upstream kernel. In addition, if you are running an older kernel that is part of your distro, you may still want some of the features (like new hardware enablement) that is not available on your kernel release. These are two reasons that we release the ROCK driver separately rather than relying entirely on upstream kernel releases.

This is a long-winded way of trying to say that the benefits of ROCm 1.9 vs. upstream that is listed on the current ROCm page are not a permanent list of stuff we are trying to cordon off. Rather, they're things that aren't in the upstream kernel *yet*.

Somewhat of a side note: it's not like we have a "custom kernel" anymore. We dropped that back in ROCm 1.7. Rather, we now have a modified set of driver modules that are built using DKMS against whatever kernel version you're running. Any kernel versions that we list at a ROCm release are specifically the kernel versions we've tested a release against -- for example, we internally tested ROCm 1.9 against Ubuntu 18.04.1 LTS before releasing it, so we're sure that our drivers will build against and run on the Ubuntu kernel version that is current as of release time.

This does not mean that you couldn't build our DKMS modules against a more modern kernel. It's just that we may not have tested them, and you may need a small patch here and there in case there are some kernel changes that break the DKMS build.

Note: what I've said above is my understanding of the situation, but may not accurately represent AMD's official stance. You may want to wait for confirmation from elsewhere before taking any of this as gospel. :)

**Comment by elukey** [comment]
@jlgreathouse I have a follow up question related to how to avoid deploying `hsa-ext-rocr-dev` if one wants to stick with open-source-only packages. As far as I can see the deb package is tightly coupled with several others:

```
apt-cache rdepends hsa-ext-rocr-dev
hsa-ext-rocr-dev
Reverse Depends:
  hsa-rocr-dev
  rocm-dev
  hcc
```

What is the best practice for people using the Debian repositories/packages? Would it be possible to have a release of rocm that leaves `hsa-ext-rocr-dev` not required by any package, and to be installed optionally if needed?
