### ISSUE TITLE
Question: Finalizer Extension in ROCm 1.9

### ISSUE THREAD

**Issue by koerberm** [RadeonOpenCompute/ROCR-Runtime#43]
Hi,

with ROCm 1.9 the package "hsa-ext-rocr-dev" does not contain the finalizer extension (ibhsa-ext-finalize64.so) anymore and the vector copy sample was removed from the runtime. 
Did you remove this extension completely or was it moved to a different package?

Regards
Michael

**Comment by jlgreathouse** [comment]
Hi @koerberm 

Yes, we removed the HSAIL finalizer from ROCm as of 1.9.0. As such, we also removed the HSAIL-using example code. This was part of our effort to make ROCm completely open source; our finalizer had code that AMD did not wish to open source, so we have moved our stack away from needing it.

Basically all of ROCm's compilers are built on LLVM now, and go straight from language to machine code through LLVM IR.

**Comment by koerberm** [comment]
Hi @jlgreathouse 

Thanks for your quick reply! Is there still a way to compile HSAIL code into executable code objects with those compilers? And if so, can you give a hint on how to do that?

Thanks
Michael

**Comment by jlgreathouse** [comment]
Hi @koerberm 

As of ROCm 1.9, when we removed the closed-source HSAIL finalizer from our ROCm distribution, we no longer include a path to compile HSAIL to executable code objects.

**Comment by koerberm** [comment]
Oh, that's bad. I have some HSAIL code making use of HSA signals and cross-lane instructions. Are those features supported by HCC or another Compiler you support?Am 19.09.2018 17:27 schrieb Joseph Greathouse <notifications@github.com>:Hi @koerberm
As of ROCm 1.9, when we removed the closed-source HSAIL finalizer from our ROCm distribution, we no longer include a path to compile HSAIL to executable code objects.

**Comment by gstoner** [comment]
@koerberm    LLVM Native give you more control over Cross Lane Instructions and it still uses Signals

**Comment by jlgreathouse** [comment]
Hi @koerberm 

If you're looking for cross-lane instructions, these can be implemented on our new compiler stack using [inline assembly](https://gpuopen.com/amdgcn-assembly/). More specifically, this blog post talks about how to do [cross-lane ops](https://gpuopen.com/amd-gcn-assembly-cross-lane-operations/). Because our compiler infrastructure all goes through LLVM, you can use normal syntax such as `__asm__ volatile("gcn_asm_string_goes_here" : out_constraint : in_constraint : clobber_list);`

Documentation:

- [LLVM assembly syntax for GCN](https://llvm.org/docs/AMDGPUOperandSyntax.html)
- [An example application of how to write inline assembly](https://github.com/ROCm-Developer-Tools/HIP/tree/master/samples/2_Cookbook/10_inline_asm)
- [The Vega ISA manual](https://developer.amd.com/wordpress/media/2017/08/Vega_Shader_ISA_28July2017.pdf) which describes the syntax of cross-lane ops such as `ds_swizzle`, `ds_permute`, `ds_bpermute`, and the DPP modifier to vector opcodes
- Rather than using direct assembly, you could also use an LLVM builtin to get access to DPP MOV operations to move data between lanes. [This is described here](https://github.com/llvm-mirror/clang/blob/release_70/include/clang/Basic/BuiltinsAMDGPU.def#L115).
- [Here is an example of doing a full reduction using inline assembly from MIOpen](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/e3fb49c07358adc0e4c6fe6cf9b258aa2b936ea9/src/kernels/MIOpenBatchNormBwdSpatial.cl#L197)

**Comment by jlgreathouse** [comment]
As for the use of HSA signals from within your kernel, let me request some feedback from @t-tye 

I believe our LLVM branch had these as builtins at one point, but I don't know if that feature is now available in our open source compilers.

**Comment by skeelyamd** [comment]
HSA signals are supported, at minimum, through the device library "ockl".  A specific language may have wrappers for as well.

This is the link to the HSA queue and signal function headers.
https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/ockl/inc/ockl_hsa.h
