### ISSUE TITLE
Why was soversion bumped from 1.0.0 to 1.1.9 in the roc-2.1.0 release

### ISSUE THREAD

**Issue by tstellar** [RadeonOpenCompute/ROCR-Runtime#56]
Where does the 1.1.9 version come from?  Will this value be changing each ROCm release going forward?

**Comment by jlgreathouse** [comment]
Like [the Thunk](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/issues/27), ROCr was previously automatically generating its soversion from tags on an AMD-internal repository. This caused problems when rebuilding ROCr from GitHub source, since our tags are different here. So we would end up silently changing soversion each release even though perhaps nothing had changed.

For instance, releasing the `roc-2.0.0` tag bumped the major version to 2 _when building from GitHub_, but we left the released soversion as 1 when building from our internal repo. See the comments in [this temporary patch](https://github.com/RadeonOpenCompute/Experimental_ROC/blob/roc-2.0.0/distro_install_scripts/shared_files/patches/rocr_cmake.patch) for a bit more detail.

Instead, we're trying to make our soversion major, minor and patch numbers [semantically meaningful](https://semver.org/ )going forward. As such, the patch version may change if we've made patches, but the major version shouldn't change unless we make API-breaking changes (for example).

**Comment by tstellar** [comment]
@jlgreathouse OK, that makes sense, thanks.
